/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zutchiSol from "./zutchi.sol";
export type { zutchiSol };
export type { MockZIRCUIT } from "./MockZIRCUIT";
